Makefile

Play nice if /bin/sh is not bash (like on Ubuntu, where it is linked to /bin/dash)

Use bash as shell

---

.gitignore

Better gitignore, if working with Windows.
Exclude vim backup files.

Add windows exe and vim backups to gitignore

---

.gitignore

Reorganized .gitignore based on template from https://www.gitignore.io/api/go
Added *.out for coverage output

Reorganize .gitignore, added *.out

---

.travis.yml
Makefile
README.md
bootstrap/cmd/bootstrap-build/main.go
bootstrap/cmd/bootstrap-pigeon/main.go
doc.go
main.go

pigeon already heavily depends on goimports (e.g. in the Makefile) and also suggests the user to use it to cleanup the generated code. The integration of the functionality of goimports is very easy (actually only creating a buffer and execute one call to `imports.Process` so I feel it is worth it to integrate this functionality directly into pigeon.
It is my opinion, pigeon should generate valid code directly.

Integrate goimports functionality

---

Makefile
bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
doc.go
pigeon.go
test/errorpos/errorpos.go
test/errorpos/errorpos.peg
test/errorpos/errorpos_test.go

The parser stores the farthest position together with the expected
values, just before the backtracking starts. If the parsing fails,
this position together with the expected values are returned
as the error instead of the generic "1:1 (0): no match found".
Fixes #18

Better error reporting based on farthest parse pos

---

Makefile
bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
builder/static_code.go
doc.go
examples/calculator/calculator.go
examples/calculator/calculator_test.go
examples/json/json.go
main.go
parse_test.go
pigeon.go
test/andnot/andnot.go
test/andnot/andnot_test.go
test/errorpos/errorpos.go
test/errorpos/errorpos.peg
test/errorpos/errorpos_test.go
test/issue_1/issue_1.go
test/issue_12/issue_12.go
test/issue_18/issue_18.go
test/issue_18/issue_18.peg
test/issue_18/issue_18_test.go
test/linear/linear.go
test/predicates/predicates.go

Add FailureTracking as flag to pigeon and to existing tests and examples.
Builds on #24 
Fixes #18

Add FailureTracking as flag to pigeon and to existing tests and examples.

---

Makefile
builder/builder.go
builder/generated_static_code.go
builder/static_code.go
doc.go
examples/json/json_test.go
examples/json/optimized/json.go
main.go

If the `-optimize-parser` flag is provided to pigeon, the resulting
parser is generated without the the Debug and Memoize options.
This saves a few cpu cycles, when using the generated parser,
because some checks for those options are not present.

Added `-optimize-parser` flag

---

ast/ast_walk.go

This is highly influenced by the `go/ast` package.

Add ast.Walk function to traverse pigeon AST

---

Makefile
bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
builder/builder.go
builder/generated_static_code.go
builder/generated_static_code_range_table.go
builder/static_code.go
builder/static_code_range_table.go
doc.go
examples/calculator/calculator.go
examples/json/json.go
examples/json/optimized/json.go
main.go
pigeon.go
targeted_test.go
test/andnot/andnot.go
test/errorpos/errorpos.go
test/global_store/global_store.go
test/goto/goto.go
test/issue_1/issue_1.go
test/issue_12/issue_12.go
test/issue_18/issue_18.go
test/linear/linear.go
test/predicates/predicates.go

With the flag `-optimize-basic-latin` set, the parser generates
a lookup table for the Unicode Basic Latin characters for each
character class matcher, which speeds up the parsing for data,
which consists mainly of characters from this range.

Add `-optimize-basic-latin' parser optimization

---

Makefile
ast/ast_optimize.go
ast/ast_optimize_test.go
doc.go
examples/json/json_test.go
examples/json/optimized-grammar/json.go
main.go

The ast package is extended with an Optimize function,
which walks the given AST and applies several optimizations.
For the optimization, the following actions are taken:
* removal of unreferenced rules
* replace rule references with a copy of the referenced Rule, if the
referenced rule it self has no references.
* resolve nested choice expressions
* resolve choice expressions with only one alternative
* resolve nested sequences expression
* resolve sequence expressions with only one element
* combine character class matcher and literal matcher, where possible
The resulting grammar is usually more memory consuming, but faster for parsing.
With the added flag `-optimize-grammar`, pigeon is instructed to generate
a parser with optimized grammar.

Optimize grammar and `-optimize-grammar` flag

---

bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
builder/generated_static_code.go
builder/static_code.go
doc.go
examples/calculator/calculator.go
examples/calculator/calculator_test.go
examples/json/json.go
examples/json/json_test.go
examples/json/optimized-grammar/json.go
examples/json/optimized/json.go
pigeon.go
targeted_test.go
test/andnot/andnot.go
test/errorpos/errorpos.go
test/global_store/global_store.go
test/goto/goto.go
test/issue_1/issue_1.go
test/issue_12/issue_12.go
test/issue_18/issue_18.go
test/linear/linear.go
test/max_expr_cnt/maxexpr.go
test/predicates/predicates.go

This PR implements a statistic feature for the ordered choice expressions, which helps the author of a PEG grammar to optimize the parsing by order the alternatives in an ordered choice expression by their frequency  (most used alternatives first).

Statistics for ordered choice expressions

---

Makefile
ast/ast_optimize.go
bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
builder/generated_static_code.go
builder/static_code.go
doc.go
examples/calculator/calculator.go
examples/json/json.go
examples/json/optimized-grammar/json.go
examples/json/optimized/json.go
main.go
pigeon.go
test/alternate_entrypoint/altentry.go
test/alternate_entrypoint/altentry.peg
test/alternate_entrypoint/altentry_test.go
test/andnot/andnot.go
test/errorpos/errorpos.go
test/global_store/global_store.go
test/goto/goto.go
test/issue_1/issue_1.go
test/issue_18/issue_18.go
test/labeled_failures/labeled_failures.go
test/linear/linear.go
test/max_expr_cnt/maxexpr.go
test/predicates/predicates.go
test/runeerror/runeerror.go
test/thrownrecover/thrownrecover.go

This is the companion PR to issue #44 . See the issue for an overview of the problem it solves. The implementation is mostly complete (as described in #44), with documentation and tests, there's one TODO left to optimize validation that the alternate entrypoints are valid rule names, I'll address it if the PR looks good otherwise.

implement the alternate entrypoints feature

---

bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
builder/generated_static_code.go
builder/static_code.go
doc.go
examples/calculator/calculator.go
examples/indentation/indentation.go
examples/json/json.go
examples/json/optimized-grammar/json.go
examples/json/optimized/json.go
pigeon.go
targeted_test.go
test/alternate_entrypoint/altentry.go
test/andnot/andnot.go
test/errorpos/errorpos.go
test/global_store/global_store.go
test/goto/goto.go
test/goto_state/goto_state.go
test/issue_1/issue_1.go
test/issue_18/issue_18.go
test/labeled_failures/labeled_failures.go
test/linear/linear.go
test/max_expr_cnt/maxexpr.go
test/predicates/predicates.go
test/runeerror/runeerror.go
test/runeerror/runeerror.peg
test/runeerror/runeerror_test.go
test/state/state.go
test/stateclone/stateclone.go
test/statereadonly/statereadonly.go
test/thrownrecover/thrownrecover.go

This option allows parsers to be used on documents that contain invalid UTF-8.
The invalid bytes match the any matcher and behave like a U+FFFD for the character class matcher.
The actual U+FFFD is never returned, the invalid bytes are instead. This allows to validate for example signatures on the partially invalid text.

Add AllowInvalidUTF8 option

---

Makefile
ast/ast_optimize.go
ast/ast_walk.go
test/state/state.go

The new backtrack-aware state code block causes a panic when building with the `-optimize-grammar` option because the new AST node was not added to the AST-walking switch. This PR fixes it.

fix panic when state code block used with the -optimize-grammar option

---

Makefile
bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
builder/generated_static_code.go
builder/static_code.go
examples/calculator/calculator.go
examples/indentation/indentation.go
examples/json/json.go
examples/json/optimized-grammar/json.go
examples/json/optimized/json.go
pigeon.go
test/alternate_entrypoint/altentry.go
test/andnot/andnot.go
test/emptystate/emptystate.go
test/emptystate/emptystate.peg
test/emptystate/emptystate_test.go
test/errorpos/errorpos.go
test/global_store/global_store.go
test/goto/goto.go
test/goto_state/goto_state.go
test/issue_1/issue_1.go
test/issue_18/issue_18.go
test/labeled_failures/labeled_failures.go
test/linear/linear.go
test/max_expr_cnt/maxexpr.go
test/predicates/predicates.go
test/runeerror/runeerror.go
test/state/state.go
test/stateclone/stateclone.go
test/statereadonly/statereadonly.go
test/thrownrecover/thrownrecover.go

As discussed in #52 , the `emptyState` optimization (where a pre-allocated empty map is returned when cloning the backtrack-aware global state if it is empty) can cause issues if the state code blocks remove keys at some point. 
The sequence to reproduce the issue is detailed in #52, copied here for convenience and implemented in the `test/emptystate/emptystate.peg` test grammar:
* an expression causes the parser to clone with no state (p.cur.state is empty) so it returns emptyState, and then on restore it sets p.cur.state to the same as emptyState (an alias)
* state code block adds something (state["thing"] = 1), emptyState no longer empty (because p.cur.state is an alias)
* an expression causes the parser to clone state["thing"] == 1, then backtracks and restores the clone (p.cur.state …

Remove emptyState optimization

---

bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
builder/builder.go
builder/generated_static_code.go
builder/static_code.go
doc.go
examples/calculator/calculator.go
examples/indentation/indentation.go
examples/json/json.go
examples/json/optimized-grammar/json.go
examples/json/optimized/json.go
pigeon.go
test/alternate_entrypoint/altentry.go
test/andnot/andnot.go
test/emptystate/emptystate.go
test/errorpos/errorpos.go
test/global_store/global_store.go
test/goto/goto.go
test/goto_state/goto_state.go
test/issue_1/issue_1.go
test/issue_18/issue_18.go
test/labeled_failures/labeled_failures.go
test/linear/linear.go
test/max_expr_cnt/maxexpr.go
test/predicates/predicates.go
test/runeerror/runeerror.go
test/state/state.go
test/stateclone/stateclone.go
test/statereadonly/statereadonly.go
test/thrownrecover/thrownrecover.go

@mna I quickly put together the idea of optimizing the global state handling by removing all the not necessary code, if the state change expression is not used by a generated parser, as suggested by you in https://github.com/mna/pigeon/pull/52#issuecomment-340593754.
What do you think?

optimize global state if not used

---

.travis.yml
README.md

Due to changes in golang.org/x/tools/imports/...
Adjust tested versions of Go in travisci.

Change required version of Go to 1.9.x

---

.travis.yml
Makefile
README.md
go.mod
go.sum

Hi, I am packaging pigeon for [nixpkgs](https://github.com/NixOS/nixpkgs).
This makes the builds more reproducible by pinning the dependencies with go
modules. And also helps me to package future releases quicker.
This requires a version of Go 1.11 or higher to work properly.

use go modules

---

bootstrap/cmd/bootstrap-pigeon/bootstrap_pigeon.go
grammar/bootstrap.peg

This is a PR that addresses the issue I had with compiling the first fix in #115. This is a separate bug and does not close #115, but only enables a fix for #115.
Firstly, it fixes incorrect quote escapes for interpreted string literals and rune literals, which were swapped (in interpreted strings `\'` could be escaped and rune literals `\"` could be escaped; the opposite would be correct).
Secondly, it fixes raw strings being limited to a one rune length, due to a missing `*`.
If I understand correctly, the tests in the `test` directory only test `grammar/pigeon.peg` but not `grammar/bootrap.peg`. Therefore, I'm not sure where and if to test this.

bootstrap.peg: Fix incorrect quote escapes and raw string length

---

.github/workflows/go-cross.yml

* This was missed at https://github.com/mna/pigeon/pull/162
* This change should provoke less warnings in GitHub actions

Update actions/cache to v4
